"""

Utilities for preparing and running metsim

"""

from pathlib import Path
import xarray as xr
import numpy as np
from collections import OrderedDict
import yaml
try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
    
from metsim import MetSim
#Add  the parent directory to the path
import sys
sys.path.append(str(Path(__file__).parent.parent))
import gpep_to_summa_utils as gts_utils

def create_metsim_config(config, input_forcing_file, input_state_file, output_file):
    """Create metsim configuration file, both from master configuration file and from hardwired settings"""
    
    # Read base configuration from yaml file
    with open(config['metsim_base_config']) as file:
        metsim_base_config = OrderedDict(yaml.load(file, Loader=yaml.FullLoader))

    #Derive start and end time from forcing file
    start_time, end_time = gts_utils.get_time_range(input_forcing_file)
    metsim_base_config["start"] = str(start_time)
    metsim_base_config["stop"] = str(end_time)

    # Set input forcing and state
    metsim_base_config["forcing"] = str(input_forcing_file)
    metsim_base_config["state"] = str(input_state_file)

    # Set domain file and output file path
    metsim_base_config["domain"] = str(Path(config['metsim_dir'],config["metsim_domain_nc"]))
    output_file_path = Path(output_file)
    metsim_base_config['out_dir'] = str(output_file_path.parent)
    
    #Set other settings
    metsim_base_config["out_freq"] = config['out_freq']
    metsim_base_config["scheduler"] = "threading"
    metsim_base_config['time_step'] = str(config['metsim_timestep_minutes'])

    # Create MetSim object
    ms = MetSim(metsim_base_config)

    return ms

def rename_metsim_output(ms,new_file_name):
    ms_output = [ms._get_output_filename(times) for times in ms._times]

    if len(ms_output) == 1:
        ms_output_file = Path(ms_output[0])
        ms_output_file.rename(new_file_name)
    elif len(ms_output) > 1:
        output = xr.open_mfdataset(ms_output,combine='nested',concat_dim='time')
        output.to_netcdf(new_file_name)
        #Delete ms_output files
        for file in ms_output:
            Path(file).unlink()
    elif len(ms_output) == 0:
        raise ValueError("No output files were generated by MetSim")

    return

def create_state_file(input_forcing_file, output_state_file,timestep_hrs=24):
    # Open the input file
    ds = xr.open_dataset(input_forcing_file)
    # Get the time variable
    time_var = ds['time']
    # Get the number of records
    nrecs = len(time_var)
    # Get the start time of the original file
    end_time = time_var[-1].values
    # Select the last 90 days of data
    data = ds.sel(time=slice(end_time - np.timedelta64(89 * 24 * 3600, 's'), end_time))
    # Shift the time nrecs days previously
    data['time'] = data['time'] - np.timedelta64(nrecs * timestep_hrs * 3600, 's')
    # Output the data to a new file
    data.to_netcdf(output_state_file)
    
    return

def subset_domain_to_forcing(domain_input_nc, forcing_file, domain_subset_nc):
    """Subset domain file to forcing with smaller domain"""

    # Open NetCDF to xarray dataset
    domain_ds = xr.open_dataset(domain_input_nc)
    forcing_ds = xr.open_dataset(forcing_file)

    # Return only domain hrus that match the forcing hrus
    domain_subset = domain_ds.where(domain_ds.hruId.isin(forcing_ds.hruId), drop=True)
    # Trim further to only remaining grus. Otherwise drop of gru could be used.
    domain_gru = domain_subset.gruId.where(
        domain_ds.gruId.isin(domain_subset.hru2gruId), drop=True
    )
    domain_subset["gruId"] = domain_gru[0]

    # Sort by hruId
    domain_subset = domain_subset.sortby("hruId")

    # Set filename and output to netcdf
    domain_subset.to_netcdf(domain_subset_nc)

    domain_ds.close()
    forcing_ds.close()

    return

def correct_temperature(input_file, corrected_file, offset):
    """
    Corrects the minimum temperature in the dataset if it is higher than the maximum temperature,
    but only for specific timesteps and HRUs where this occurs. Logs the corrections.

    Parameters:
    file_path (str): The path to the NetCDF file.
    offset (float): The offset to subtract from the maximum temperature to set the minimum temperature.
    """
    # Load the dataset
    data = xr.open_dataset(input_file)

    # Check and correct temperatures
    with data as ds:
        tmax = ds['tmax']
        tmin = ds['tmin']

        # Log and correct tmin where the error condition is true
        corrections_log = []
        # Iterate over time and ID dimensions
        for time in ds.time:
            for hru in ds.hru:
                if tmax.sel(time=time, hru=hru) < tmin.sel(time=time,hru=hru):
                    corrected_value = tmax.sel(time=time, hru=hru) - offset
                    ds['tmin'].loc[{'time': time, 'hru': hru}] = corrected_value
                    corrections_log.append((time.values, hru.values, corrected_value.values))


        # Save the corrected dataset to a new file
        ds.to_netcdf(corrected_file)

    if corrections_log:
        print("Corrections made at:")
        for log in corrections_log:
            print(f"Time: {log[0]}, HRU ID: {log[1]}, Corrected Tmin: {log[2]}")
    else:
        print("No corrections were necessary.")