# Settings for the test case generation of summa forcing data from gpep forcing

# To initiate a new run, review and update the settings below.
# Note that values will be available as a primary key i.e. config['case_name']


base_settings:
  case_name: tuolumne
  base_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/ensemble_generation/rf_best_regression_static_dynamic/
gis_data:
  catchment_shp: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/gis/tuolumne_tdx.gpkg
  attribute_nc: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/gis/attributes.nc
  summa_gru_csv: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/gis/stations_with_hru_ids.csv
  base_10_grus: 3
grid_data:
  grid_input_dir: /anvil/projects/x-ees240082/users/dcasson/era5/tuolumne
  grid_output_dir: /anvil/projects/x-ees240082/users/dcasson/era5/tuolumne/remapped
  grid_temp_dir: /anvil/projects/x-ees240082/users/dcasson/era5/tuolumne/remapped/temp
  grid_file_name: tuolumne_processed.nc
  grid_input_var: 
    - CaSR_v3.1_P_UVC_10m
    - CaSR_v3.1_A_PR0_SFC
    - CaSR_v3.1_P_TT_1.5m
    - CaSR_v3.1_P_P0_SFC
    - CaSR_v3.1_P_FI_SFC
    - CaSR_v3.1_P_FB_SFC
    - CaSR_v3.1_P_HU_1.5m
  wind_var: windspd
gpep_to_summa_paths:
  gpep_forcing_dir: /ensembles/
  gpep_to_summa_output_dir: /gpep_to_summa/
  metsim_dir: /gpep_to_summa/metsim/
  metsim_input_dir: /gpep_to_summa/metsim/input/
  metsim_output_dir: /gpep_to_summa/metsim/output/
  easymore_dir: /gpep_to_summa/easymore/
  summa_forcing_dir: /summa/forcing/
  summa_det_forcing_dir: /anvil/projects/x-ees240082/users/dcasson/era5/tuolumne/remapped/final/
  summa_det_output_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/ensemble_generation/era5_remapped/summa_output/
  summa_output_dir: /summa/output/
metsim_settings:
  metsim_base_config: '/home/x-dcasson/GitRepos/gpep_to_summa_snakemake/workflow/config/metsim_base_config.yaml'
  catchment_shp_hru_id_field: 'HRU_ID'
  catchment_shp_lat_id_field: 'latitude'
  catchment_shp_lon_id_field: 'longitude'
  # The forcing shp will be located in the easymore_intersect_dir
  forcing_shp: forcing_shp.shp # Default value
  metsim_timestep_minutes: 60
  metsim_domain_nc: domain.nc # Default value
  out_freq: Y
easymore_settings:
  easymore_input_var:
  - prcp
  - t_max
  - t_min
summa_paths:
  summa_exe: /anvil/projects/x-ees240082/apps/summa_repos/summa_develop_sundials/summa/bin/summa_sundials.exe
  summa_settings_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/summa/settings/
  file_manager: /anvil/projects/x-ees240082/users/dcasson/gpep/tuolumne/summa/settings/fileManager.txt