# Settings for the test case generation of summa forcing data from gpep forcing

# To initiate a new run, review and update the settings below.
# Note that values will be available as a primary key i.e. config['case_name']

<<<<<<< HEAD
case_name: gpep_hydrofabric_test
gpep_forcing_dir: /scratch/dcasson/gpep/transform_tests_yearly/
working_dir: /scratch/dcasson/gpep/transform_tests_yearly/
summa_dir: /scratch/dcasson/gpep/transform_tests_yearly//test/summa/
summa_forcing_dir: /scratch/dcasson/gpep/transform_tests_yearly/test/summa
input_files:
catchment_shp: /home/dcasson/gpep_to_summa/gpkg/tuolumne_hydrofabric_gru.gpkg
attribute_nc: /home/dcasson/gpep_to_summa/gpkg/tuolumne_hydrofabric_gru_attributes.nc
metsim_base_config: ../config/metsim_base_config.yaml
catchment_shp_hru_id_field: 'HRU_ID'
catchment_shp_lat_id_field: 'latitude'
catchment_shp_lon_id_field: 'longitude'
# The forcing shp will be located in the easymore_intersect_dir
forcing_shp: forcing_shp.shp # Default value
easymore_input_var:
- prcp
- t_max
- t_min
metsim_timestep_minutes: 180
metsim_domain_nc: domain.nc # Default value
out_freq: Y
=======
base_settings:
  case_name: gpep_rf_ens
key_directories:
  gpep_forcing_dir: /Users/drc858/Data/gpep/from_HPC/
  working_dir: /Users/drc858/Data/hydrofabric/forcing_data
  summa_dir: /Users/drc858/Data/hydrofabric/forcing_data/summa/
  summa_forcing_dir: /Users/drc858/Data/hydrofabric/forcing_data/summa
input_files:
  catchment_shp: /Users/drc858/Data/summa_snakemake/hydrofabric_tuolumne/watershed_tools/results/hru_lev0_final.gpkg
  attribute_nc: /Users/drc858/GitHub/hydrofabric_to_summa/data/tuolumne/summa/settings/attributes.nc
  metsim_base_config: ../config/metsim_base_config.yaml
easymore:
  catchment_shp_hru_id_field: 'HRU_ID'
  catchment_shp_lat_id_field: 'latitude'
  catchment_shp_lon_id_field: 'longitude'
  # The forcing shp will be located in the easymore_intersect_dir
  forcing_shp: forcing_shp.shp # Default value
  easymore_input_var:
    - prcp
    - t_max
    - t_min
metsim:
  metsim_timestep_minutes: 60
  metsim_domain_nc: domain.nc # Default value
  out_freq: Y
>>>>>>> bf3c0ac1546e051a798a7833879626a56d1205fb
