# Settings for the test case generation of summa forcing data from gpep forcing

# To initiate a new run, review and update the settings below.
# Note that values will be available as a primary key i.e. config['case_name']

base_settings:
  case_name: bow
  base_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/ensemble_generation/lwr_best_regression_static_dynamic/
gis_data:
  catchment_shp: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/gis/bow_tdx.gpkg
  attribute_nc: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/gis/attributes.nc
wind_data:
  wind_input_dir: /anvil/projects/x-ees240082/users/dcasson/casr/bow/
  wind_output_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/ensemble_generation/wind/
  wind_temp_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/ensemble_generation/wind/temp/
  wind_input_var: 
  - CaSR_v3.1_P_UVC_10m
  wind_output_var: 
  - windspd
gpep_to_summa_paths:
  gpep_forcing_dir: /ensembles/
  gpep_to_summa_output_dir: /gpep_to_summa/
  metsim_dir: /gpep_to_summa/metsim/
  metsim_input_dir: /gpep_to_summa/metsim/input/
  metsim_output_dir: /gpep_to_summa/metsim/output/
  easymore_dir: /gpep_to_summa/easymore/
  summa_forcing_dir: /summa/forcing/
  summa_output_dir: /summa/output/
metsim_settings:
  metsim_base_config: '/home/x-dcasson/GitRepos/gpep_to_summa_snakemake/workflow/config/metsim_base_config.yaml'
  catchment_shp_hru_id_field: 'HRU_ID'
  catchment_shp_lat_id_field: 'latitude'
  catchment_shp_lon_id_field: 'longitude'
  # The forcing shp will be located in the easymore_intersect_dir
  forcing_shp: forcing_shp.shp # Default value
  metsim_timestep_minutes: 60
  metsim_domain_nc: domain.nc # Default value
  out_freq: Y
easymore_settings:
  easymore_input_var:
  - prcp
  - t_max
  - t_min
summa_paths:
  summa_exe: /anvil/projects/x-ees240082/apps/summa_repos/summa_develop_sundials/summa/bin/summa_sundials.exe
  summa_settings_dir: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/summa/settings/
  file_manager: /anvil/projects/x-ees240082/users/dcasson/gpep/bow/summa/settings/fileManager.txt
